name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  #########################################################
  # Compile Job:
  # Install dependencies and compile debug and test sources
  #########################################################
  compile:
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane Compile lane
        run: fastlane compile